### ISSUE TITLE
How to achieve global uniqueness of certain properties?

### ISSUE THREAD

**Issue by LuboO** [LuboO/iCalendar-parser_PA193_Rteam#3]
UID property must be unique in whole VCALENDAR object. Any suggestions on how to achieve that (maybe global variable?)?

**Comment by WOnder93** [comment]
I think the best solution would be to create a class that would track the UIDs and pass a reference via the 'parse' method calls. If the same UID is then registered a second time, it would throw an exception. I could try coding it today - I need a similar thing for TZID property in the VTIMEZONE component. It shouldn't be much work.

**Comment by LuboO** [comment]
that would mean changing all parse functions?

**Comment by WOnder93** [comment]
not all, just those that can have the UID (resp. TZID) property somewhere in their hierarchy
