### ISSUE TITLE
Add constant NAME member to params/props/components

### ISSUE THREAD

**Issue by WOnder93** [LuboO/iCalendar-parser_PA193_Rteam#4]
I think it would be nice to have a (public) "static const char *NAME = ..." constant under each parameter/property/component class, which the parent properties/components would reference instead of just hard-coding the same constant all over the place.

What do you think?

**Comment by LuboO** [comment]
i also thought about that, i can do that later today.

**Comment by LuboO** [comment]
Resolved in 1d0c1d2c576d2bc24697750a06f17062fffff4e4
